### ISSUE TITLE
Darker Code Highlights

### ISSUE THREAD

**Issue by chase** [docpad/website#20]
Most color schemes don't work to well with the light gold colored background.

Zenburn seems to work very well with the them for the rest of the site and need only be used for the `pre code` blocks.

Perhaps we could use that as the color scheme?

**Comment by balupton** [comment]
Will be shutting down the docpad website and switching it to gitbook instead, making this issue deprecated.

Details here: https://discuss.bevry.me/t/migration-to-gitbook-for-all-documentation/270?u=balupton
