### ISSUE TITLE
Rethink the website design

### ISSUE THREAD

**Issue by balupton** [docpad/website#47]
I really dig these:

- the ubuntu website http://www.ubuntu.com/desktop/ 
  - bit cluttered but really nice
- ubuntu support page http://community.ubuntu.com/help-information/finding-help/support/
  - love the cleaness of this design and professional yet fun type
- canonical partners http://www.canonical.com/partners
  - we need a page like this that appeals to enterprise
- google+ http://google.com/+
  - I like the pop of the content, boxes and menu in contrast to the background
- noflo js website http://noflojs.org/documentation/ - source http://noflojs.org/documentation/
  - all round beautiful and well done
- jawbone up https://jawbone.com/up
  - love the header image, topbar and the presentation of the information, keeps you engaged, reading everything, and makes you really want it
- ghost http://tryghost.org/features.html
  - everything about this I love!
- sassy https://github.com/docpad/gui/issues/1
  - love the colours and pop of the saasy designs
- buffer jobs http://jobs.bufferapp.com/backend-hacker
  - crisp clean and professional, nice use of layout and images
- http://www.webpop.com/
- http://roots.cx/
  - clear, concise, informative, and well marketed homepage for a ssg

What I hate about our current site:

- so bland, there is no colour
- the colour doesn't communicate our values of openness, collaboration and possibility, instead it feels like a jail cell
- the font type isn't professional, instead it is loud and cluttered
- logo is blurry, text should be text not an image
- doesn't appeal to anyone but early adopters

Things I hate:

- https://mixpanel.com/help/reference/creating-a-profile - looks just as bland as our website, just different colours to be bland to
- https://github.com/bevry/docpad-website/issues/ - again really really bland and hurts my eyes at night time due to the amount of white light

**Comment by mikeumus** [comment]
Ported to https://discuss.bevry.me/t/docpad-org-design-refresh/51

**Comment by balupton** [comment]
https://github.com/docpad/website/issues/71
