### ISSUE TITLE
Start making "official" tutorials

### ISSUE THREAD

**Issue by greduan** [docpad/website#53]
@balupton 
I am constantly looking for useful stuff and today I found [Kirby](http://getkirby.com/), a file based CMS. (No, not that Kirby. :wink:)

Anyway, one thing I noticed and that I liked is that the dev asks the users what they would like to see a tutorial about next, and whatever grabs his attention or is most requested he does a [tutorial on the blog](http://getkirby.com/).

Thought why don't we do something similar? In this case it would probably be me doing some of the tutorials, but I still think it's nice to have something like this.

**Comment by balupton** [comment]
Will be shutting down the docpad website and switching it to gitbook instead, making this issue deprecated.

Details here: https://discuss.bevry.me/t/migration-to-gitbook-for-all-documentation/270?u=balupton
