### ISSUE TITLE
Any way to test?

### ISSUE THREAD

**Issue by Zearin** [docpad/website#58]
I’m interested in improving the styles (and I **love** that you wrote them in Stylus! ☺).  

But since the site is stitched together from a few repositories, I don’t know how to tell if my changes break the build or not.

Is there a way for me to test the build?  (Sorry if it the answer is obvious, but I’m still learning Node/CoffeeScript conventions…)

**Comment by balupton** [comment]
`npm test` can now be used, as seen by our new travis workflow
