### ISSUE TITLE
404 documentation link

### ISSUE THREAD

**Issue by burdiyan** [docpad/website#67]
Link for documentation on the web site is not working: https://docpad.org/docs

**Comment by Greduan** [comment]
Oh nay! @balupton

**Comment by balupton** [comment]
The actual pages are working, just not the index page... very strange. Can someone on the @docpad/core-team look into this? I'm a bit busy with some other library updates right now.

**Comment by Greduan** [comment]
I'm not sure what could be the issue. I don't have DocPad installed to check if the website renders correctly, either. Although I could never get it to render correctly.

@burdiyan When did you notice this issue? Did the page work correctly before?

**Comment by Greduan** [comment]
I'm looking at the commits of this repo and I can't find anything that would break the index page.

Perhaps one of the plugins isn't working?

@balupton who has access to the DocPad website?

**Comment by burdiyan** [comment]
@Greduan just right now. If you enter to https://docpad.org/docs you will find 404. This page was working correctly before, but the last time a saw it was quite a long time ago, so have no idea actually when it was broken.

**Comment by Greduan** [comment]
@burdiyan OK. Thank you. :)
