### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by telekosmos** [docpad/website#69]
Hi there
I am trying to deploy the website in my local machine in a nginx virtual host (docpad.dev :-P). The point is only the landing page works, when you click a link a (big) 404 error, as you can see:

```
~/Dev/docpad/website $ curl -X GET http://docpad.dev/docs/install
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.4.3</center>
</body>
</html>
```

This is after generating the static site as is in the [Deploy to a static server](https://docpad.org/docs/deploy)  by running `docpad generate --env static` and copying into the mapped local directory. In this section doesn't say anything about virtual host deployment, so I'd like to know whether or not this is a kind of bug, VH deployment is not supported or I'm kind of dumb (as usual...)

Thanks in advance

**Comment by balupton** [comment]
Not sure why, but perhaps it is this. If you are running it on a static environment, be sure to add `--env static`, as otherwise URL redirects won't have files created for them.

**Comment by balupton** [comment]
closing due to age
